### ISSUE TITLE
[REQUEST] Please specify Roadmap for the project

### ISSUE THREAD

**Issue by kimjiwongit** [guger/MoneyBook#19]
I tested the Android App. It requires multiple null checks for example for displayName otherwise it crashes.

The app looks beautiful! What's the roadmap or future of the app? Are you planning to update it?

I loved your work though incomplete! Thank you!

**Comment by guger** [comment]
Thank you, I'm happy to hear positive feedback! :)

Well as shown in the README, this app is in an early development stage, and there are lots of unfinished apis.
This app will be a future predecessor of my current "MoneyBook" app available in Google Play.

I'm working on this in my rare free time, so there're time-slots, where I'm not able to actively develop on this project.
Currently, I'm working on re-implementing all features from the app which is in production. For further details, please have a look at my project [MoneyBook 2.0.0](https://github.com/guger/MoneyBook/projects/1).

If you've any ideas to improve my project, or you found some bugs, feel free to contact me, every feedback is welcome. You can also open a pull request if you want, but please keep in mind that the architecture is not really stable yet, and there can be breaking changes, especially until I reach [MoneyBook 2.0.0 Preview 1](https://github.com/guger/MoneyBook/milestone/1). This will be the first release of this new app, published as a beta version in Google Play.

**Comment by kimjiwongit** [comment]
Thank you! I am looking forward to the progress for learning purpose! 
Waiting for the milestone and stable version.
